import {RouteAuths} from './globalProps';
import {ColumnsType} from "antd/es/table";
import React from "react";
function permitablePageList():RouteAuths[]{
    let idCounter = 1;
    const Pages: RouteAuths[] = [{
        id: idCounter++,
        page_name:'Meldingen',
        path:'/tickets',
        read:true,
        write:false,
        delete:false,
    },{
        id: idCounter++,
        page_name: 'Bedrijven',
        path:'/clients',
        read:false,
        write:false,
        delete:false,
        children: [
            {
                id: idCounter++,
                page_name: 'Meldingen',
                path:'#meldingen',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Notes',
                path:'#notes',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Locatie',
                path:'#locatie',
                read:false,
                write:false,
                delete:false,
                children: [
                    {
                        id: idCounter++,
                        page_name: 'Rooms',
                        path:'#rooms',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Meldingen',
                        path:'#meldingen',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Prices',
                        path:'#prices',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Members',
                        path:'#members',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Projects',
                        path:'#projects',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Contracts',
                        path:'#contracts',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Contact Person',
                        path:'#contactPerson',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Planing',
                        path:'#planing',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Staff',
                        path:'#staff',
                        read:false,
                        write:false,
                        delete:false,
                    },
                ]
            },
            {
                id: idCounter++,
                page_name: 'Projects',
                path: '#projects',
                read: false,
                write: false,
                delete: false,
            },
            {
                id: idCounter++,
                page_name: 'Contracts',
                path:'#contracts',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Contactpersonen',
                path:'#contactPerson',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Facturen',
                path:'#faturalar',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Eenheidsprijzen',
                path:'#fiyatlar',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Kwaliteitsrapport',
                path:'#kaliteRaporu',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Gespreksrapport',
                path:'#konuşmaRaporu',
                read:false,
                write:false,
                delete:false,
            },
        ]
    },{
        id: idCounter++,
        page_name: 'Gebouwen',
        path:'/locations',
        read:false,
        write:false,
        delete:false,
        children: [
            {
                id: idCounter++,
                page_name: 'Rooms',
                path:'#rooms',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Meldingen',
                path:'#meldingen',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Klants',
                path: '#klants',
                read: false,
                write: false,
                delete: false,
            },
            {
                id: idCounter++,
                page_name: 'Prices',
                path:'#prices',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Members',
                path:'#members',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Projects',
                path:'#projects',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Contracts',
                path:'#contracts',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Contact Person',
                path:'#contactPerson',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Planing',
                path:'#planing',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Staff',
                path:'#staff',
                read:false,
                write:false,
                delete:false,
            },
        ]
    },{
        id: idCounter++,
        page_name:'Medewerkers',
        path: '/medewerkers',
        read:false,
        write:false,
        delete:false,
    },{
        id: idCounter++,
        page_name:'UserManagment',
        path:'/userboard',
        read:false,
        write:false,
        delete:false,
    }];
    return Pages;
}
function permitableContactPersonList():RouteAuths[]{
    let idCounter = 1;
    const Pages: RouteAuths[] = [{
        id: idCounter++,
        page_name:'Meldingen',
        path:'/tickets',
        read:true,
        write:false,
        delete:false,
    },{
        id: idCounter++,
        page_name: 'Bedrijven',
        path:'/clients',
        read:false,
        write:false,
        delete:false,
        children: [
            {
                id: idCounter++,
                page_name: 'Meldingen',
                path:'#meldingen',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Notes',
                path:'#notes',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Contracts',
                path:'#contracts',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Contactpersonen',
                path:'#contactPerson',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Facturen',
                path:'#faturalar',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Eenheidsprijzen',
                path:'#fiyatlar',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Kwaliteitsrapport',
                path:'#kaliteRaporu',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Gespreksrapport',
                path:'#konuşmaRaporu',
                read:false,
                write:false,
                delete:false,
            },
            {
                id: idCounter++,
                page_name: 'Locatie',
                path:'#locatie',
                read:false,
                write:false,
                delete:false,
                children: [
                    {
                        id: idCounter++,
                        page_name: 'Rooms',
                        path:'#rooms',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Meldingen',
                        path:'#meldingen',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Prices',
                        path:'#prices',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Members',
                        path:'#members',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Projects',
                        path:'#projects',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Contracts',
                        path:'#contracts',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Contact Person',
                        path:'#contactPerson',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Planing',
                        path:'#planing',
                        read:false,
                        write:false,
                        delete:false,
                    },
                    {
                        id: idCounter++,
                        page_name: 'Staff',
                        path:'#staff',
                        read:false,
                        write:false,
                        delete:false,
                    },
                ]
            },
        ]
    }];
    return Pages;
}
export {permitablePageList, permitableContactPersonList}
